server:
  port: 9002

spring:
  application:
    name: pagebook-profile
  rabbitmq:
    host: localhost
    username: pagebook
    password: pagebook
    virtual-host: /
  datasource:
    url: jdbc:postgresql://localhost:5432/profile
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info