server:
  port: 8771

spring:
  application:
    name: pagebook-business
  data:
    mongodb:
      host: localhost
      port: 27017
      database: business
      repositories:
        enabled: true

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info

