server:
  port: 8773

spring:
  application:
    name: pagebook-stories
  rabbitmq:
    host: localhost
    username: pagebook
    password: pagebook
    virtual-host: /
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stories
      repositories:
        enabled: true

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://10.177.2.29:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
